/* confdefs.h */
#define PACKAGE_NAME "zeromq"
#define PACKAGE_TARNAME "zeromq"
#define PACKAGE_VERSION "3.2.4"
#define PACKAGE_STRING "zeromq 3.2.4"
#define PACKAGE_BUGREPORT "zeromq-dev@lists.zeromq.org"
#define PACKAGE_URL ""
#define PACKAGE "zeromq"
#define VERSION "3.2.4"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_LIBPTHREAD 1
#define ZMQ_HAVE_OSX 1
#define STDC_HEADERS 1
#define HAVE_ERRNO_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_LIMITS_H 1
#define HAVE_IFADDRS_H 1
#define ZMQ_HAVE_IFADDRS 1
#define HAVE_SYS_UIO_H 1
#define ZMQ_HAVE_UIO 1
#define HAVE_STDBOOL_H 1
#define TIME_WITH_SYS_TIME 1
